# Copy book ex.

In [215]:
import numpy as np

In [216]:
A = np.array([[1,2,3],
              [0, 4, 5],
              [1, 1, 7]])

In [217]:
np.linalg.inv(A)     #inverse a matrix A

array([[ 1.0952381 , -0.52380952, -0.0952381 ],
       [ 0.23809524,  0.19047619, -0.23809524],
       [-0.19047619,  0.04761905,  0.19047619]])

In [218]:
A = np.array([[2, 3],
             [4, 5]])
B = np.array([[1, 0],
             [2, 7]])

In [219]:
X = np.linalg.solve(A, B)

In [220]:
print(X)

[[ 0.5 10.5]
 [ 0.  -7. ]]


In [221]:
X = np.linalg.solve(B,A)

In [222]:
print(X)

[[ 2.          3.        ]
 [-0.         -0.14285714]]


In [223]:
A = np.array([[1, 0, 3],
             [2, 1, 5],
             [4, 2, 1]])
B= np.array([[2, 1, 1],
            [1, 2, 3],
            [0, 4, 5]])

In [224]:
X = np.linalg.solve(A, B)

In [225]:
print(X)

[[ 1.33333333  1.          0.66666667]
 [-2.77777778 -0.          1.11111111]
 [ 0.22222222  0.          0.11111111]]


In [226]:
X= np.linalg.solve(B,A)

In [227]:
print(X)

[[ 0.  -0.2  2. ]
 [ 1.   0.  -6. ]
 [ 0.   0.4  5. ]]


In [228]:
A = np.array([[12, 4],
             [3, 8]])

In [229]:
print(np.linalg.matrix_power(A, 4))  # A Matrix power 

[[29136 18560]
 [13920 10576]]


In [230]:
B = np.array([[5, 6, 3], 
             [-1, 0, 1], 
             [1, 2, -1]])

In [231]:
print(np.linalg.matrix_power(B, 2)) # B Matrix power

[[22 36 18]
 [-4 -4 -4]
 [ 2  4  6]]


In [232]:
print(np.linalg.det(A))   # Matrix determinant

83.99999999999999


In [246]:
# W3resource

In [234]:
print(np.__version__)  # print numoy version

2.0.0


In [235]:
Lst = [1, 2, 3, 4]

In [236]:
A = np.array(Lst)  # list to array

In [237]:
print(A)

[1 2 3 4]


In [238]:
A = ([[12, 4],
      [3, -8]])

In [239]:
eigenvalues, eigenvectors = np.linalg.eig(A)

In [240]:
print('Eigenvalues:', eigenvalues)
print('Eigenvectors as columns:\n', eigenvectors)

Eigenvalues: [12.58300524 -8.58300524]
Eigenvectors as columns:
 [[ 0.98954457 -0.19076621]
 [ 0.14422742  0.9816355 ]]


In [241]:
B = np.array([[5, 6, 3],
             [-1, 0, 1],
             [1, 2, -1]])

In [242]:
eigenvalues, eigenvectors = np.linalg.eig(B)

In [274]:
A = np.arange(2, 11).reshape(3,3)

In [275]:
print(A)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [276]:
n1 = np.zeros(10)

In [277]:
print(n1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [278]:
n1[6] = 11

In [279]:
print(n1)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [287]:
print(z)

NameError: name 'z' is not defined

In [288]:
z = z[::-1]

NameError: name 'z' is not defined

In [289]:
print(z)

NameError: name 'z' is not defined